plugin.py

MsgType004d device annouce  …
Transcodage + checksum  …
Add domoticz.debug
Calcul checksum OK
Maj Zigateconf
Suppression du fichier debug  …
Interroge le capteur nouvellement associer sur ces EP  …
Desactivation interrogation capteur par EP
Fix issue 4  …
Ajout detection type device (xiaomi)  …
Maj capteur lumi.weather et lumi.sensor.ht
Fix Maj battery LVL
Fix detecteur ouverture/fermeture et capteur de presence  …
Ajout support interrupteur (v1 et v2)
Amelioration decoupage a la reception  …

Dev Maj 1.0.3

---

plugin.py

Ajout du capteur : lumi.sensor_motion.aq2  pir et Lux sensor fonctionnel  yyeeaahh !

Adding lumi.sensor_motion.aq2 full fonction

---

plugin.py

Adding xiaomi 86sw1 switch as a PushOn switch

Adding xiaomi 86sw1 switch

---

Domoticz-ZigateUSB/plugin.py
Domoticz-ZigateWIFI/plugin.py

Il avait disparu sur ta derniere mise a jour

retour du 86sw1 dans la version usb et wifi

---

Domoticz-ZigateUSB/plugin.py

retour diu 86sw1 pour lupdate du switch

retour du 86sw1

---

Domoticz-ZigateUSB/plugin.py

Update lumi.sensor_switch.aq2 & lumi.sensor_switch to selector switch

Update lumi.sensor_switch.aq2 & lumi.sensor_switch

---

Domoticz-ZigateUSB/plugin.py

Selector switch for 86sw2 et aqara switch v1 & v2
full fonctionnel

Selector switch for 86sw2 et aqara switch v1 & v2

---

Domoticz-ZigateUSB/plugin.py

Ajout lumi.sensor_cube sans les rotations

Ajout lumi.sensor_cube sans les rotations

---

Domoticz-ZigateUSB/plugin.py

fix #39
fix #31
add water sensor #37

version 1.0.8

---

zigate.py

Implémentation du dictionnaire pour appeler les fonctions.
Implémentation des fonctions "DecodeXXXX"

Creation zigate.py

---

plugin.py

Ce patch corrige une erreur d'affichage du debug car 'Bar_for' n'est pas un type String.

Fix: Set Bar_forecast to string

---

plugin.py

When using Set Level , update the Domoticz Device with the corresponding level value.

In Set Level, update the DomoDevice with the corresponding level

---

plugin.py

Le plugin provoque des erreurs qui gène fortement son fonctionnement (mise en boucle).
Le commit gère proprement les erreurs dans les messages (try except pour la plupart) afin de ne pas entraîner de fonctionnement erratique du plugin.
Attention cela ne règle pas le problème de fond.
En plus : gestion des valeurs aberrantes de températures (>10^35) en insérant un max à 1000°C.
Version du plugin : 2.3.5
Version du firmware zigate : 3.0d
Capteurs utilisés : aqara temp+hum+baro, aqara switch door, aqara mouvement

Sortie propre sur des keyerror et value error

---

plugin.py

Le système est instable avec la correction des températures >1000°C. Il faut que je revoie la correction, dans l'attente, je fais une retour arrière.

Retour arrière sur la gestion des températures aberrantes

---

plugin.py

See #103 , print the Zigate Firmware version at startup.

Print Firmware Version of Zigate hardware

---

onMessage.txt

Document call flow in onMessage call back

Document call flow in onMessage call back

---

Control-des-Volets.txt
plugin.py

This address : 
#106 
#105 
#83

Implement the monitoring of the Profalux Shutter in case of out-domoticz changes

---

plugin.py

Reverts sasu-drooz/Domoticz-Zigate#143
Issue in MajDomoDevice missing parameter

Revert "Update plugin.py"

---

PluginConf.txt
plugin.py
z_heartbeat.py
z_output.py
z_tools.py
z_var.py

ix a problem if the structutre is not yet in place
request readattribute for Xiaomi Magnet every 50'

Request ReadAttribute to Xiaomi Magnet every 50' 

---

z_input.py
z_tools.py

Update z_tools updSQN
log activity for Decode8000 message
add Message Type in strutcutred log

push several fix

---

Compatible-Hardware.md

Add various full working tested devices

Update Compatible Hardware

---

Compatible-Hardware.md

Tested and fonctionnal Xiaomi 86sw1 switch as a Push On

adding 86sw1

---

Compatible-Hardware.md

Adding : LED1649C5
